"""Shared Galaxea A1 runtime constants."""

from __future__ import annotations

ARM_JOINT_COUNT = 6
GRIPPER_JOINT_COUNT = 1
TOTAL_JOINT_COUNT = ARM_JOINT_COUNT + GRIPPER_JOINT_COUNT

IDLE_TIMEOUT_CODE = 1 << 6

DEFAULT_MAX_EEF_DELTA_M = 0.03
DEFAULT_MAX_ROT_DELTA_RAD = 0.15

LEROBOT_BASELINE = "0.6.x"
LEROBOT_DATASET_FORMAT = "v3.0"
