# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from galaxea_a1_protocol.v1 import a1_runtime_pb2 as lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lerobot_robot_galaxea_a1/runtime/v1/a1_runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A1RuntimeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Describe = channel.unary_unary(
                '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Describe',
                request_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.DescribeRequest.SerializeToString,
                response_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.DescribeResponse.FromString,
                _registered_method=True)
        self.Open = channel.unary_unary(
                '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Open',
                request_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.OpenRequest.SerializeToString,
                response_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.OpenResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Heartbeat',
                request_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Observe = channel.unary_unary(
                '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Observe',
                request_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.SerializeToString,
                response_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.ValuesResponse.FromString,
                _registered_method=True)
        self.Command = channel.unary_unary(
                '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Command',
                request_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.CommandRequest.SerializeToString,
                response_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.ValuesResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Health',
                request_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.SerializeToString,
                response_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Close',
                request_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class A1RuntimeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Describe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Open(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A1RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Describe': grpc.unary_unary_rpc_method_handler(
                    servicer.Describe,
                    request_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.DescribeRequest.FromString,
                    response_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.DescribeResponse.SerializeToString,
            ),
            'Open': grpc.unary_unary_rpc_method_handler(
                    servicer.Open,
                    request_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.OpenRequest.FromString,
                    response_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.OpenResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Observe': grpc.unary_unary_rpc_method_handler(
                    servicer.Observe,
                    request_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.FromString,
                    response_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.ValuesResponse.SerializeToString,
            ),
            'Command': grpc.unary_unary_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.CommandRequest.FromString,
                    response_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.ValuesResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.FromString,
                    response_serializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.HealthResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A1RuntimeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Describe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Describe',
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.DescribeRequest.SerializeToString,
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.DescribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Open(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Open',
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.OpenRequest.SerializeToString,
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.OpenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Heartbeat',
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Observe',
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.SerializeToString,
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.ValuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Command',
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.CommandRequest.SerializeToString,
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.ValuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Health',
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.SerializeToString,
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lerobot_robot_galaxea_a1.runtime.v1.A1RuntimeService/Close',
            lerobot__robot__galaxea__a1_dot_runtime_dot_v1_dot_a1__runtime__pb2.SessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
