cmake_minimum_required(VERSION 3.16)
project(a1_observation_bridge)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(ros1_bridge REQUIRED)
find_ros1_package(roscpp REQUIRED)
add_executable(a1_observation_bridge main.cpp)
ament_target_dependencies(a1_observation_bridge rclcpp ros1_bridge ros1_roscpp)
install(TARGETS a1_observation_bridge DESTINATION bin)
