// Generated by scripts/runtime/render_foxglove_layout.py; do not edit.
export const WORKFLOW_STATUS_TOPIC = "/a1/ops/workflow_status";
export const COLLECTION_SERVICES = {
  start: "/a1/ops/collection/start",
  save: "/a1/ops/collection/save",
  discard: "/a1/ops/collection/discard",
  reset: "/a1/ops/collection/reset",
  stop: "/a1/ops/collection/stop",
} as const;
