name: check

on:
  push:
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - uses: extractions/setup-just@v3
      - name: Install FFmpeg
        run: |
          sudo apt-get update -qq
          sudo apt-get install --yes --no-install-recommends ffmpeg
      - name: Install Python
        run: uv python install 3.12
      - name: Install project
        env:
          UV_DEFAULT_INDEX: https://pypi.org/simple
          UV_TORCH_BACKEND: cpu
        run: uv sync --frozen --python 3.12
      - name: Check
        run: just check
